name: 5. Sync Upstream
on:
  schedule:
    - cron: '0 3 * * *' # Daily sync
  workflow_dispatch:

env:
  UPSTREAM_URL: "https://github.com/Artificial-Pancreas/iAPS.git"
  WORKFLOW_TOKEN: ${{ secrets.GH_PAT }}
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "ipa-only" # Sync official code directly into your custom branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: Artificial-Pancreas/sync-upstream-repo@master
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
